/**
 * @file index.test.ts
 * Tests for index module exports, errors, and convertDocxToText convenience API.
 */

import { writeFile, unlink, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import JSZip from 'jszip';
import {
  convertDocxToText,
  convertDocxFile,
  convertDocxToTypst,
  getHeadingLevel,
  DocxReadError,
  DocxParseError,
  parseXml,
  readDocxFile,
  extractText,
  extractNumberingMaps,
  resolveListItems,
  extractTables,
  convertTableToTypst,
  findImagesInRun,
  extractImageMetadata,
  saveImages,
} from '../index.js';

describe('index and high-level API', () => {
  const testDir = join(tmpdir(), 'docx2typst-index-test-' + Date.now());
  const validDocxPath = join(testDir, 'test.docx');
  const listDocxPath = join(testDir, 'list-test.docx');

  beforeAll(async () => {
    await mkdir(testDir, { recursive: true });
    const zip = new JSZip();
    zip.file(
      'word/document.xml',
      `<?xml version="1.0" encoding="UTF-8"?>
      <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
        <w:body>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="Heading1"/>
            </w:pPr>
            <w:r><w:t>Heading Paragraph</w:t></w:r>
          </w:p>
          <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t>Body Paragraph</w:t></w:r>
          </w:p>
        </w:body>
      </w:document>`,
    );
    const buffer = await zip.generateAsync({ type: 'nodebuffer' });
    await writeFile(validDocxPath, buffer);

    const listZip = new JSZip();
    listZip.file(
      'word/document.xml',
      `<?xml version="1.0" encoding="UTF-8"?>
      <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
        <w:body>
          <w:p>
            <w:pPr>
              <w:numPr>
                <w:ilvl w:val="0"/>
                <w:numId w:val="1"/>
              </w:numPr>
            </w:pPr>
            <w:r><w:t>First bullet</w:t></w:r>
          </w:p>
          <w:p>
            <w:pPr>
              <w:numPr>
                <w:ilvl w:val="1"/>
                <w:numId w:val="1"/>
              </w:numPr>
            </w:pPr>
            <w:r><w:t>Nested bullet</w:t></w:r>
          </w:p>
          <w:p>
            <w:pPr>
              <w:numPr>
                <w:ilvl w:val="0"/>
                <w:numId w:val="2"/>
              </w:numPr>
            </w:pPr>
            <w:r><w:t>Numbered item</w:t></w:r>
          </w:p>
        </w:body>
      </w:document>`,
    );
    listZip.file(
      'word/numbering.xml',
      `<?xml version="1.0" encoding="UTF-8"?>
      <w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
        <w:abstractNum w:abstractNumId="10">
          <w:lvl w:ilvl="0"><w:numFmt w:val="bullet"/></w:lvl>
          <w:lvl w:ilvl="1"><w:numFmt w:val="bullet"/></w:lvl>
        </w:abstractNum>
        <w:abstractNum w:abstractNumId="20">
          <w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/></w:lvl>
        </w:abstractNum>
        <w:num w:numId="1"><w:abstractNumId w:val="10"/></w:num>
        <w:num w:numId="2"><w:abstractNumId w:val="20"/></w:num>
      </w:numbering>`,
    );
    const listBuffer = await listZip.generateAsync({ type: 'nodebuffer' });
    await writeFile(listDocxPath, listBuffer);
  });

  afterAll(async () => {
    try {
      await unlink(validDocxPath);
      await unlink(listDocxPath);
    } catch {
      // Ignore cleanup errors
    }
  });

  it('should export all public APIs', () => {
    expect(typeof convertDocxToText).toBe('function');
    expect(typeof convertDocxFile).toBe('function');
    expect(typeof convertDocxToTypst).toBe('function');
    expect(typeof getHeadingLevel).toBe('function');
    expect(typeof readDocxFile).toBe('function');
    expect(typeof extractText).toBe('function');
    expect(typeof extractNumberingMaps).toBe('function');
    expect(typeof resolveListItems).toBe('function');
    expect(typeof parseXml).toBe('function');
    expect(typeof extractTables).toBe('function');
    expect(typeof convertTableToTypst).toBe('function');
    expect(typeof findImagesInRun).toBe('function');
    expect(typeof extractImageMetadata).toBe('function');
    expect(typeof saveImages).toBe('function');
    expect(DocxReadError).toBeDefined();
    expect(DocxParseError).toBeDefined();
  });

  it('should convert a docx file directly to text', async () => {
    const text = await convertDocxToText(validDocxPath);
    expect(text).toBe('Heading Paragraph\nBody Paragraph');
  });

  it('should convert a docx file directly to Typst document', async () => {
    const typstDoc = await convertDocxFile(validDocxPath, { includeHeader: true });
    expect(typstDoc.content).toBe(
      '// Generated by docx2typst\n\n= Heading Paragraph\n\n*Body Paragraph*',
    );
    expect(typstDoc.stats).toEqual({
      paragraphCount: 1,
      headingCount: 1,
      runsWithFormatting: 1,
    });
  });

  it('should convert a docx file with lists to Typst document and text', async () => {
    const text = await convertDocxToText(listDocxPath);
    expect(text).toBe('First bullet\nNested bullet\nNumbered item');

    const typstDoc = await convertDocxFile(listDocxPath);
    expect(typstDoc.content).toBe('- First bullet\n\n  - Nested bullet\n\n+ Numbered item');
    expect(typstDoc.stats.paragraphCount).toBe(3);
  });

  it('should preserve error cause in DocxReadError', () => {
    const cause = new Error('Underlying read failed');
    const err = new DocxReadError('File read failure', { cause });
    expect(err.name).toBe('DocxReadError');
    expect(err.message).toBe('File read failure');
    expect(err.cause).toBe(cause);
    expect(err instanceof DocxReadError).toBe(true);
    expect(err instanceof Error).toBe(true);
  });

  it('should preserve error cause in DocxParseError', () => {
    const cause = new Error('Underlying parse failed');
    const err = new DocxParseError('Parsing failure', { cause });
    expect(err.name).toBe('DocxParseError');
    expect(err.message).toBe('Parsing failure');
    expect(err.cause).toBe(cause);
    expect(err instanceof DocxParseError).toBe(true);
    expect(err instanceof Error).toBe(true);
  });
});
