#!/usr/bin/env node
/**
 * @file cli.ts
 * Standalone CLI executable for converting .docx files to Typst markup.
 */

import process from 'node:process';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import {
  convertDocxToText,
  convertDocxToTypst,
  extractNumberingMaps,
  extractText,
  readDocxFile,
  resolveListItems,
  saveImages,
} from './index.js';
import type { DocxImage } from './types.js';
import { DocxParseError, DocxReadError } from './errors.js';

/**
 * Parsed command-line options.
 */
export interface CliOptions {
  files: string[];
  textOnly: boolean;
  stdout: boolean;
  header: boolean;
  imagesDir: string;
  noEscape: boolean;
  help: boolean;
  version: boolean;
}

/**
 * Parses command-line arguments manually without external dependencies.
 *
 * @param args - Array of command-line argument strings (excluding node and script paths).
 * @returns Parsed CLI configuration options.
 */
export function parseCliArgs(args: string[]): CliOptions {
  const options: CliOptions = {
    files: [],
    textOnly: false,
    stdout: false,
    header: false,
    imagesDir: 'images',
    noEscape: false,
    help: false,
    version: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg === '-h' || arg === '--help') {
      options.help = true;
    } else if (arg === '-v' || arg === '--version') {
      options.version = true;
    } else if (arg === '--text-only') {
      options.textOnly = true;
    } else if (arg === '--stdout') {
      options.stdout = true;
    } else if (arg === '--header') {
      options.header = true;
    } else if (arg === '--no-escape') {
      options.noEscape = true;
    } else if (arg === '--images-dir') {
      if (i + 1 < args.length && !args[i + 1].startsWith('-')) {
        options.imagesDir = args[++i];
      } else {
        throw new Error('Option "--images-dir" requires a directory path argument.');
      }
    } else if (arg.startsWith('--images-dir=')) {
      const val = arg.slice('--images-dir='.length);
      if (val.length === 0) {
        throw new Error('Option "--images-dir" requires a directory path argument.');
      }
      options.imagesDir = val;
    } else if (arg.startsWith('-')) {
      console.error(`Warning: Unrecognized option "${arg}".`);
    } else {
      options.files.push(arg);
    }
  }

  return options;
}

/**
 * Prints CLI usage information to standard output.
 */
export function printHelp(): void {
  console.log(`Usage: docx2typst [options] <files...>

Convert .docx files to Typst markup format.

Arguments:
  <files...>            One or more .docx file paths to convert

Options:
  --text-only           Use convertDocxToText instead of convertDocxFile (output plain text)
  --stdout              Print output to stdout instead of writing file
  --header              Include '// Generated by docx2typst' header in output
  --images-dir <dir>    Directory for extracted images (default: 'images')
  --no-escape           Disable special character escaping
  -h, --help            Print usage and exit
  -v, --version         Print version from package.json and exit`);
}

/**
 * Retrieves the version string from package.json.
 *
 * @returns Promise resolving to the package version string.
 */
export async function getVersion(): Promise<string> {
  const candidateDirs: string[] = [];

  if (process.argv[1]) {
    const scriptDir = path.dirname(process.argv[1]);
    candidateDirs.push(path.resolve(scriptDir, '..'));
    candidateDirs.push(scriptDir);
  }

  candidateDirs.push(process.cwd());

  for (const dir of candidateDirs) {
    try {
      const pkgPath = path.join(dir, 'package.json');
      const content = await readFile(pkgPath, 'utf-8');
      const data = JSON.parse(content) as { name?: string; version?: string };
      if (data.name === 'docx2typst' && typeof data.version === 'string') {
        return data.version;
      }
    } catch {
      // Continue to next candidate directory
    }
  }

  return '0.1.0';
}

/**
 * Main execution entry point for the CLI tool.
 *
 * @param args - Argument array passed to the CLI.
 * @returns Promise resolving to the process exit code (0 for success, 1 for failure).
 */
export async function runCli(args: string[]): Promise<number> {
  let options: CliOptions;
  try {
    options = parseCliArgs(args);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`Error: ${message}`);
    return 1;
  }

  if (options.help) {
    printHelp();
    return 0;
  }

  if (options.version) {
    const version = await getVersion();
    console.log(version);
    return 0;
  }

  if (options.files.length === 0) {
    printHelp();
    console.log('No files converted.');
    return 1;
  }

  let successCount = 0;

  for (const filePath of options.files) {
    try {
      const parsed = path.parse(filePath);
      const outputPath = path.join(parsed.dir, `${parsed.name}.typ`);

      let content: string;
      if (options.textOnly) {
        let text = await convertDocxToText(filePath, {
          images: { outputDir: options.imagesDir },
        });
        if (options.header) {
          text = `// Generated by docx2typst\n\n${text}`;
        }
        content = text;
      } else {
        const rawContent = await readDocxFile(filePath);
        let docxDoc = extractText(
          rawContent.documentXml,
          { stylesXml: rawContent.stylesXml },
          rawContent.imageMap,
          rawContent.hyperlinkMap
        );
        if (rawContent.numberingXml) {
          const { numIdMap, abstractNumMap, abstractNumFmtMap } = extractNumberingMaps(
            rawContent.numberingXml,
          );
          docxDoc = resolveListItems(docxDoc, numIdMap, abstractNumMap, abstractNumFmtMap);
        }
        const typstDoc = convertDocxToTypst(docxDoc, {
          includeHeader: options.header,
          imageOutputDir: options.imagesDir,
          escapeSpecialChars: !options.noEscape,
        });

        // Collect all DocxImage objects from all paragraphs and table cells that have images
        const allImages: DocxImage[] = [];
        for (const p of docxDoc.paragraphs) {
          if (p.images && p.images.length > 0) {
            allImages.push(...p.images);
          }
        }
        if (docxDoc.tables) {
          for (const tbl of docxDoc.tables) {
            for (const row of tbl.rows) {
              for (const cell of row.cells) {
                for (const p of cell.paragraphs) {
                  if (p.images && p.images.length > 0) {
                    allImages.push(...p.images);
                  }
                }
              }
            }
          }
        }

        const uniqueImages = Array.from(
          new Map(allImages.map((img) => [img.zipPath, img])).values(),
        );

        if (uniqueImages.length > 0 && rawContent.zipInstance) {
          const absoluteImagesDir = path.resolve(path.dirname(outputPath), options.imagesDir);
          await saveImages(uniqueImages, rawContent.zipInstance, absoluteImagesDir);
        }

        content = typstDoc.content;
      }

      if (options.stdout) {
        console.log(content);
        successCount++;
      } else {
        try {
          await writeFile(outputPath, content, 'utf-8');
          successCount++;
        } catch (writeError: unknown) {
          const writeMsg = writeError instanceof Error ? writeError.message : String(writeError);
          console.error(`Failed to write file "${outputPath}": ${writeMsg}`);
        }
      }
    } catch (err: unknown) {
      if (err instanceof DocxReadError || err instanceof DocxParseError) {
        console.error(err.message);
      } else if (err instanceof Error) {
        console.error(err.message);
      } else {
        console.error(String(err));
      }
    }
  }

  if (successCount > 0) {
    console.log(`Converted ${successCount} file(s) successfully.`);
    return 0;
  } else {
    console.log('No files converted.');
    return 1;
  }
}

/* istanbul ignore next */
const isExecutedDirectly =
  typeof process.argv[1] === 'string' &&
  (process.argv[1].endsWith('cli.js') ||
    process.argv[1].endsWith('cli.ts') ||
    process.argv[1].endsWith('docx2typst'));

if (isExecutedDirectly) {
  /* istanbul ignore next */
  runCli(process.argv.slice(2))
    .then((exitCode) => {
      process.exit(exitCode);
    })
    .catch((err: unknown) => {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`Unexpected error: ${msg}`);
      process.exit(1);
    });
}
